homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include_dir_merge_named customize/

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password  
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yamaha
    - harmony

# Enables support for tracking state changes over time
history:

recorder:

# View all events in a logbook
logbook:

system_health:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

# Components
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - host: !secret xiaomi_aqara_gateways_host
      mac: !secret xiaomi_aqara_gateways_mac
      key: !secret xiaomi_aqara_gateways_key

hue:
  bridges:
   - host: !secret hue_bridges_host
     allow_unreachable: true

zwave:
   usb_path: /dev/ttyAMA0
   network_key: !secret zwave_network_key

notify:
  - name: sms
    platform: free_mobile
    username: !secret notify_username
    access_token: !secret notify_access_token
  - name: ios
    platform: ios
    service: !secret notify_ios_service
  - platform: html5
    name: html5
    vapid_pub_key: !secret notify_html5_vapid_pub_key
    vapid_prv_key: !secret notify_html5_vapid_prv_key
    vapid_email: !secret notify_html5_vapid_email

ios:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

owntracks:

device_tracker:
  - platform: icloud
    username: !secret device_tracker_icloud_username
    password: !secret device_tracker_icloud_password
    account_name: !secret device_tracker_icloud_account_name
  - platform: netgear
    host: 192.168.1.1
    username: !secret device_tracker_netgear_username
    password: !secret device_tracker_netgear_password

# remote:
#   - platform: harmony
#     name: Living Room
#     host: !secret remote_host
#     activity: ""

logger:
  default: info

homekit:
  auto_start: False
  filter:
    include_entities:
      # Hallway
      - light.hallway_lights
      # Dining room
      - light.dining_room_lights
      - cover.dining_room
      # Living room
      - light.living_room_lights
      # Kitchen
      - light.kitchen_lights
      - cover.kitchen
      # Bathroom
      - light.bathroom_lights
      # WC
      - light.wc_lights
      # Landing
      - light.landing_lights
      - cover.landing
      # Bedroom
      - light.bedroom_lights
      - light.bedroom_bedlights
      - light.bedroom_desk
      - cover.bedroom
      # Desk
      - light.desk_lights
      - cover.desk
      # Loft
      - light.loft_lights
  entity_config:
    # Hallway
    light.hallway_lights:
      name: Hallway lights
    # Dining room
    light.dining_room_lights:
      name: Dining room lights
    cover.dining_room:
      name: Dining room cover
    # Living room
    light.living_room_lights:
      name: Living room lights
    # Kitchen
    light.kitchen_lights:
      name: Kitchen lights
    cover.kitchen:
      name: Kitchen cover
    # Bathroom
    light.bathroom_lights:
      name: Bathroom lihgts
    # WC
    light.wc_lights:
      name: WC lights
    # Landing
    light.landing_lights:
      name: Landing lights
    cover.landing:
      name: Landing cover
    # Bedroom
    light.bedroom_lights:
      name: Bedroom lights
    light.bedroom_bedlights:
      name: Bedroom bedlights
    light.bedroom_desk:
      name: Bedroom desk
    cover.bedroom:
      name: Bedroom cover
    # Desk
    light.desk_lights:
      name: Desk lights
    cover.desk:
      name: Desk cover
    # Loft
    light.loft_lights:
      name: Loft lights

#influxdb:
#  host: !secret influxdb_host
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  database: !secret influxdb_database

ifttt:
  key: !secret ifttt_key

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  listen_port: !secret emulated_hue_listen_port
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false
  entities:
    # Hallway
    light.hallway_lights:
      name: Hallway lights
      hidden: false
    # Dining room
    light.dining_room_lights:
      name: Dining room lights
      hidden: false
    cover.dining_room:
      name: Dining room cover
      hidden: false
    # Living room
    light.living_room_lights:
      name: Living room lights
      hidden: false
    # Kitchen
    light.kitchen_lights:
      name: Kitchen lights
      hidden: false
    cover.kitchen:
      name: Kitchen cover
      hidden: false
    # Bathroom
    light.bathroom_lights:
      name: Bathroom lights
      hidden: false
    # WC
    light.wc_lights:
      name: WC lights
      hidden: false
    # Landing
    light.landing_lights:
      name: Landing lights
      hidden: false
    cover.landing:
      name: Landing cover
      hidden: false
    # Bedroom
    light.bedroom_lights:
      name: Bedroom lights
      hidden: false
    light.bedroom_bedlights:
      name: Bedroom bedlights
      hidden: false
    light.bedroom_desk:
      name: Bedroom desk
      hidden: false
    cover.bedroom:
      name: Bedroom cover
      hidden: false
    # Desk
    light.desk_lights:
      name: Desk lights
      hidden: false
    cover.desk:
      name: Desk cover
      hidden: false
    # Loft
    light.loft_lights:
      name: Loft lights
      hidden: false

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    # Hallway
    light.hallway_lights:
      name: Lumières
      room: Entrée
      expose: true
    # Dining room
    light.dining_room_lights:
      name: Lumières
      room: Salle à manger
      expose: true
    cover.dining_room:
      name: Volet
      room: Salle à manger
      expose: true
    # Living room
    light.living_room_lights:
      name: Lumières
      room: Salon
      expose: true
    # Kitchen
    light.kitchen_lights:
      name: Lumières
      room: Cuisine
      expose: true
    cover.kitchen:
      name: Volet
      room: Cuisine
      expose: true
    # Bathroom
    light.bathroom_lights:
      name: Lumières
      room: Salle de bain
      expose: true
    # WC
    light.wc_lights:
      name: Lumières
      room: Toilettes
      expose: true
    # Landing
    light.landing_lights:
      name: Lumières
      room: Palier
      expose: true
    cover.landing:
      name: Volet
      room: Palier
      expose: true
    # Bedroom
    light.bedroom_lights:
      name: Lumières
      room: Chambre
      expose: true
    light.bedroom_bedlights:
      name: Lampe de chevet
      room: Chambre
      expose: true
    light.bedroom_desk:
      name: Bureau
      room: Chambre
      expose: true
    cover.bedroom:
      name: Volet
      room: Chambre
      expose: true
    # Desk
    light.desk_lights:
      name: Lumières
      room: Bureau
      expose: true
    cover.desk:
      name: Volet
      room: Bureau
      expose: true
    # Loft
    light.loft_lights:
      name: Lumières
      room: Loft
      expose: true

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: !secret speedtest_server_id

clean_up_backups_service:
  host: !secret clean_up_backups_service_host
  token: !secret clean_up_backups_service_token
  number_of_backups_to_keep: 7

# Config
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensor/
group: !include_dir_merge_named groups/
history_graph: !include_dir_merge_named history_graphs/
input_boolean: !include_dir_merge_named input_boolean/
input_select: !include_dir_merge_named input_select/
input_text: !include_dir_merge_named input_text/
light: !include_dir_merge_list light/
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include_dir_merge_named shell_command/
switch: !include_dir_merge_list switch/
yeelight:
  devices: !include_dir_merge_named yeelight/
zone: !include_dir_merge_list zone/
