homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include_dir_merge_named customize/

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password  
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - yamaha

# Enables support for tracking state changes over time
history:

recorder:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Components
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - host: !secret xiaomi_aqara_gateways_host
      mac: !secret xiaomi_aqara_gateways_mac
      key: !secret xiaomi_aqara_gateways_key

hue:
  bridges:
   - host: !secret hue_bridges_host
     allow_unreachable: true

zwave:
   usb_path: /dev/ttyAMA0
   network_key: !secret zwave_network_key

notify:
  - name: sms
    platform: free_mobile
    username: !secret notify_username
    access_token: !secret notify_access_token
  - name: ios
    platform: ios
    service: !secret notify_ios_service

ios:

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: icloud
    username: !secret device_tracker_icloud_username
    password: !secret device_tracker_icloud_password
    account_name: !secret device_tracker_icloud_account_name

remote:
  - platform: harmony
    name: Living Room
    host: !secret remote_host
    activity: ""

logger:
  default: info

homekit:
  auto_start: False
  filter:
    include_entities:
      # Hallway
      - light.entree_2
      # Living room
      - light.living_room_lights
      - light.living_room_lightstrip
      - cover.fibaro__fgrm222__living_room__level
      # Dining room
      - light.dining_room_lights
      # Kitchen
      - light.kitchen_lights
      - cover.fibaro__fgrm222__kitchen__level
      # Bathroom
      - light.bathroom_lights
      # WC
      - light.wc_lights
      # Landing
      - light.escalier_2
      - cover.fibaro__fgrm222__landing__level
      # Bedroom
      - light.chambre
      - light.go
      - cover.fibaro__fgrm222__bedroom__level
      # Desk
      - light.bureau
      - cover.fibaro__fgrm222__desk__level
      # Loft
      - light.fibaro_fgd212__loft__level
  entity_config:
    # Hallway
    light.entree_2:
      name: Hallway lights
    # Living room
    light.living_room_lights:
      name: Living room lights
    cover.fibaro__fgrm222__living_room__level:
      name: Living room cover
    # Dining room
    light.dining_room_lights:
      name: Dining room lights
    # Kitchen
    light.kitchen_lights:
      name: Kitchen lights
    cover.fibaro__fgrm222__kitchen__level:
      name: Kitchen cover
    # Bathroom
    light.bathroom_lights:
      name: Bathroom lihgts
    # WC
    light.wc_lights:
      name: WC lights
    # Landing
    light.escalier_2:
      name: Landing lights
    cover.fibaro__fgrm222__landing__level:
      name: Landing cover
    # Bedroom
    light.chambre:
      name: Bedroom lights
    light.go:
      name: Bedroom bedside lamp
    cover.fibaro__fgrm222__bedroom__level:
      name: Bedroom cover
    # Desk
    light.bureau:
      name: Desk lights
    cover.fibaro__fgrm222__desk__level:
      name: Desk cover
    # Loft
    light.fibaro_fgd212__loft__level:
      name: Loft lights

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: !secret influxdb_database

ifttt:
  key: !secret ifttt_key

emulated_hue:
  host_ip: !secret emulated_hue_host_ip
  listen_port: !secret emulated_hue_listen_port
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false
  entities:
    # Hallway
    light.hallway_lights:
      name: Hallway lights
      hidden: false
    # Living room
    light.living_room_lights:
      name: Living room lights
      hidden: false
    light.living_room_lightstrip:
      name: Living room lightstrip
      hidden: false
    cover.fibaro__fgrm222__living_room__level:
      name: Living room cover
      hidden: false
    # Dining room
    light.dining_room_lights:
      name: Dining room lights
      hidden: false
    # Kitchen
    light.kitchen_lights:
      name: Kitchen lights
      hidden: false
    cover.fibaro__fgrm222__kitchen__level:
      name: Kitchen cover
      hidden: false
    # Bathroom
    light.bathroom_lights:
      name: Bathroom lights
      hidden: false
    # WC
    light.wc_lights:
      name: WC lights
      hidden: false
    # Landing
    light.landing_lights:
      name: Landing lights
      hidden: false
    cover.fibaro__fgrm222__landing__level:
      name: Landing cover
      hidden: false
    # Bedroom
    light.bedroom_lights:
      name: Bedroom lights
      hidden: false
    light.bedroom_bedlights:
      name: Bedroom bedlights
      hidden: false
    cover.fibaro__fgrm222__bedroom__level:
      name: Bedroom cover
      hidden: false
    # Desk
    light.desk_lights:
      name: Desk lights
      hidden: false
    cover.fibaro__fgrm222__desk__level:
      name: Desk cover
      hidden: false
    # Loft
    light.loft_lights:
      name: Loft lights
      hidden: false

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    # Hallway
    light.hallway_lights:
      name: Lumières
      room: Entrée
    # Living room
    light.living_room_lights:
      name: Lumières
      room: Salon
    cover.fibaro__fgrm222__living_room__level:
      name: Volet
      room: Salon
    # Dining room
    light.dining_room_lights:
      name: Lumières
      room: Salle à manger
    # Kitchen
    light.kitchen_lights:
      name: Lumières
      room: Cuisine
    cover.fibaro__fgrm222__kitchen__level:
      name: Volet
      room: Cuisine
    # Bathroom
    light.bathroom_lights:
      name: Lumières
      room: Salle de bain
    # WC
    light.wc_lights:
      name: Lumières
      room: Toilettes
    # Landing
    light.landing_lights:
      name: Lumières
      room: Palier
    cover.fibaro__fgrm222__landing__level:
      name: Volet
      room: Palier
    # Bedroom
    light.bedroom_lights:
      name: Lumières
      room: Chambre
    light.bedroom_bedlights:
      name: Go
      room: Chambre
    cover.fibaro__fgrm222__bedroom__level:
      name: Volet
      room: Chambre
    # Desk
    light.desk_lights:
      name: Lumières
      room: Bureau
    cover.fibaro__fgrm222__desk__level:
      name: Volet
      room: Bureau
    # Loft
    light.loft_lights:
      name: Lumières
      room: Loft

# Config
automation: !include_dir_merge_list automations/
binary_sensor: !include_dir_merge_list binary_sensor/
group: !include_dir_merge_named groups/
history_graph: !include_dir_merge_named history_graphs/
input_boolean: !include_dir_merge_named input_boolean/
input_select: !include_dir_merge_named input_select/
input_text: !include_dir_merge_named input_text/
light: !include_dir_merge_list light/
scene: !include_dir_merge_list scenes/
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include_dir_merge_named shell_command/
switch: !include_dir_merge_list switch/
zone: !include_dir_merge_list zone/
