- platform: yeelight
  devices:
    192.168.1.31:
      name: Bathroom 1
      use_music_mode: False
      save_on_change: True
      model: color2

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_1
