- platform: yeelight
  devices:
    192.168.1.31:
      name: Bathroom 1
      use_music_mode: True
      save_on_change: True

- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_1
