- platform: yeelight
  devices:
    192.168.1.38:
      name: Bedroom 1
      use_music_mode: False
      save_on_change: True

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_1

- platform: group
  name: Bedroom Bedlights
  entities:
    - light.go
