- platform: mqtt
  name: Bedroom Desk
  command_topic: cmnd/sonoff-bedroom-desk/POWER
  state_topic: stat/sonoff-bedroom-desk/POWER
  qos: 1
  payload_on: 'ON'
  payload_off: 'OFF'
  retain: true

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_1

- platform: group
  name: Bedroom Bedlights
  entities:
    - light.bedroom_bedside_1
