- platform: yeelight
  devices:
    192.168.1.28:
      name: Dining Room 1
      use_music_mode: True
      save_on_change: True
    192.168.1.26:
      name: Dining Room 2
      use_music_mode: True
      save_on_change: True

- platform: group
  name: Dining room Lights
  entities:
    - light.yeelight_color2_7c49ebb72e7a
    - light.yeelight_color2_7c49ebb72e78
