- platform: yeelight
  devices:
    192.168.1.32:
      name: Kitchen 1
      use_music_mode: True
      save_on_change: True
    192.168.1.33:
      name: Kitchen 2
      use_music_mode: True
      save_on_change: True

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_1
    - light.kitchen_2
