- platform: yeelight
  devices:
    192.168.1.39:
      name: Landing 1
      use_music_mode: False
      save_on_change: True
      model: color2
    192.168.1.40:
      name: Landing 2
      use_music_mode: False
      save_on_change: True
      model: color2

- platform: group
  name: Landing Lights
  entities:
    - light.landing_1
    - light.landing_2
