- platform: yeelight
  devices:
    192.168.1.12:
      name: Living Room 1
      use_music_mode: False
      save_on_change: True
    192.168.1.16:
      name: Living Room 2
      use_music_mode: False
      save_on_change: True

- platform: group
  name: Living room Lights
  entities:
    - light.living_room_1
    - light.living_room_2
