- platform: group
  name: Living room Lights
  entities:
    - light.living_room_1
    - light.living_room_2

- platform: group
  name: Living room Lightstrip
  entities:
    - light.hue_lightstrip_plus_1
