- platform: yeelight
  devices:
    192.168.1.34:
      name: WC 1
      use_music_mode: False
      save_on_change: True
      model: color2

- platform: group
  name: WC Lights
  entities:
    - light.wc_1
