- id: xiaomi_switch_1
  alias: Xiaomi Switch 1
  initial_state: "on"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.home_switch_1
        click_type: single
  action:
    - service: notify.html5
      data:
        title: Test
        message: Switch 1

- id: xiaomi_switch_2
  alias: Xiaomi Switch 2
  initial_state: "on"
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.home_switch_2
        click_type: single
  action:
    - service: notify.html5
      data:
        title: Test
        message: Switch 2

- id: cover_close
  alias: Cover close
  initial_state: "on"
  trigger:
    - platform: sun
      event: sunset
    - platform: time
      at: !secret automation_cover_close_time
  action:
    - service: cover.close_cover
      data:
         entity_id: 
           - cover.bedroom
           - cover.desk
           - cover.landing
           - cover.dining_room
    - service: notify.html5
      data:
        title: Covers
        message: Closed

- id: leave_home
  alias: Leave home
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.home_presence_detection
      from: "on"
      to: "off"
      for:
        seconds: 10
  action:
    - service: notify.html5
      data:
        title: Test
        message: Leave home

- id: at_home
  alias: At home
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: binary_sensor.home_presence_detection
      from: "off"
      to: "on"
  action:
    - service: notify.html5
      data:
        title: Test
        message: At home

- id: leave_office
  alias: Leave office
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: device_tracker.jerjako_mi9
      from: "scaleway"
      to: "not_home"
      for:
        seconds: 10
  action:
    - service: notify.html5
      data:
        title: Test
        message: Leave office

- id: at_office
  alias: At office
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: device_tracker.jerjako_mi9
      from: "not_home"
      to: "scaleway"
  action:
    - service: notify.html5
      data:
        title: Test
        message: At office

- id: home_radiators_eco
  alias: Home Radiators eco
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: input_boolean.home_radiators
      to: "off"
  action:
    - service: notify.html5
      data:
        title: Radiators
        message: Eco

- id: home_radiators_heat
  alias: Home Radiators heat
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: input_boolean.home_radiators
      to: "on"
  action:
    - service: notify.html5
      data:
        title: Radiators
        message: Heat

# Radiator Schedule
#  - At 3h00, 18° in the bedroom
#  - At 7h00, 20° in the living room
#  - At 9h30, 16° in the living room
#  - At 17h30, 20° in the living room

- id: home_radiators_schedule_eco
  alias: Home Radiators schedule eco
  initial_state: "on"
  trigger:
    - platform: time_pattern
      minutes: "/5"

    - platform: template # 03:00:00 - 18°
      value_template: "{% if states.sensor.bedroom_temperature.state|float > 18 %}true{% else %}false{% endif %}"

    - platform: template # 07:00:00 - 20°
      value_template: "{% if states.sensor.hallway_temperature.state|float > 20 %}true{% else %}false{% endif %}"

    - platform: template # 09:30:00 - 16°
      value_template: "{% if states.sensor.hallway_temperature.state|float > 16 %}true{% else %}false{% endif %}"

    - platform: template # 17:30:00 - 20°
      value_template: "{% if states.sensor.hallway_temperature.state|float > 20 %}true{% else %}false{% endif %}"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_radiators_schedule
          state: "on"
        - condition: or
          conditions:
            - condition: template
              value_template: "{% if states.sensor.hallway_temperature.state|float > 20 %}true{% else %}false{% endif %}"
            - condition: template
              value_template: "{% if states.sensor.bedroom_temperature.state|float > 20 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "03:00:00"
                  before: "07:00:00"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                - condition: template
                  value_template: "{% if states.sensor.bedroom_temperature.state|float > 18 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "07:00:00"
                  before: "09:30:00"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                - condition: template
                  value_template: "{% if states.sensor.hallway_temperature.state|float > 20 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "09:30:00"
                  before: "17:30:00"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                - condition: template
                  value_template: "{% if states.sensor.hallway_temperature.state|float > 16 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "17:30:00"
                  before: "23:59:59"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                - condition: template
                  value_template: "{% if states.sensor.hallway_temperature.state|float > 20 %}true{% else %}false{% endif %}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.home_radiators

- id: home_radiators_schedule_heat
  alias: Home Radiators schedule heat
  initial_state: "on"
  trigger:
    - platform: time_pattern
      minutes: "/5"

    - platform: template # 00:00:00 - 20°
      value_template: "{% if states.sensor.bedroom_temperature.state|float < 19.8 %}true{% else %}false{% endif %}"

    - platform: template # 03:00:00 - 18°
      value_template: "{% if states.sensor.bedroom_temperature.state|float < 17.5 %}true{% else %}false{% endif %}"
    
    - platform: template # 07:00:00 - 20°
      value_template: "{% if states.sensor.hallway_temperature.state|float < 19.8 %}true{% else %}false{% endif %}"
    
    - platform: template # 09:30:00 - 16°
      value_template: "{% if states.sensor.hallway_temperature.state|float < 15.5 %}true{% else %}false{% endif %}"
    
    - platform: template # 17:30:00 - 20°
      value_template: "{% if states.sensor.hallway_temperature.state|float < 19.8 %}true{% else %}false{% endif %}"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_radiators_schedule
          state: "on"
        - condition: or
          conditions:
            - condition: template
              value_template: "{% if states.sensor.hallway_temperature.state|float < 15.5 %}true{% else %}false{% endif %}"
            - condition: template
              value_template: "{% if states.sensor.bedroom_temperature.state|float < 15.5 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "00:00:00"
                  before: "03:00:00"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                    - sat
                    - sun
                - condition: template
                  value_template: "{% if states.sensor.bedroom_temperature.state|float < 18.5 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "03:00:00"
                  before: "07:00:00"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                    - sat
                    - sun
                - condition: template
                  value_template: "{% if states.sensor.bedroom_temperature.state|float < 17.5 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "07:00:00"
                  before: "09:30:00"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                - condition: template
                  value_template: "{% if states.sensor.hallway_temperature.state|float < 19.8 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "09:30:00"
                  before: "17:30:00"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                - condition: template
                  value_template: "{% if states.sensor.hallway_temperature.state|float < 15.5 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "17:30:00"
                  before: "23:59:59"
                  weekday:
                    - mon
                    - tue
                    - wed
                    - thu
                    - fri
                - condition: template
                  value_template: "{% if states.sensor.hallway_temperature.state|float < 19.8 %}true{% else %}false{% endif %}"
            - condition: and
              conditions:
                - condition: time
                  after: "07:00:00"
                  before: "23:59:59"
                  weekday:
                    - sat
                    - sun
                - condition: state
                  entity_id: binary_sensor.home_presence_detection
                  state: "on"
                - condition: template
                  value_template: "{% if states.sensor.hallway_temperature.state|float < 19.8 %}true{% else %}false{% endif %}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.home_radiators

# Automation for sending MQTT message on input select change
- alias: Zigbee2mqtt Log Level
  initial_state: "on"
  trigger:
    platform: state
    entity_id: input_select.zigbee2mqtt_log_level
  action:
    - service: mqtt.publish
      data:
        payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
        topic: zigbee2mqtt/bridge/config/log_level
# Automation to start timer when enable join is turned on
- id: zigbee_join_enabled
  alias: Zigbee Join Enabled
  hide_entity: true
  trigger:
    platform: state
    entity_id: switch.zigbee2mqtt_main_join
    to: "on"
  action:
    service: timer.start
    entity_id: timer.zigbee_permit_join
# Automation to stop timer when switch turned off and turn off switch when timer finished
- id: zigbee_join_disabled
  alias: Zigbee Join Disabled
  hide_entity: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
    - platform: state
      entity_id: switch.zigbee2mqtt_main_join
      to: "off"
  action:
    - service: timer.cancel
      data:
        entity_id: timer.zigbee_permit_join
    - service: switch.turn_off
      entity_id: switch.zigbee2mqtt_main_join

