- platform: template
  sensors:
    bathroom_motion_sensor_battery:
      friendly_name: Motion sensor
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.bathroom_motion_sensor.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    bathroom_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.bathroom_temperature.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    bathroom_water_leak_battery:
      friendly_name: Water leak
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.bathroom_water_leak.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    bathroom_washing_machine_power:
      friendly_name: Washing machine power
      unit_of_measurement: "w"
      value_template: "{{ states.switch.bathroom_washing_machine.attributes.current_power_w }}"
      device_class: power
