- platform: template
  sensors:
    dining_room_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.dining_room_temperature.attributes.battery_level }}"
      device_class: battery
