- platform: template
  sensors:
    hallway_door_battery:
      friendly_name: Door
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.hallway_door.attributes.battery_level }}"
      icon_template: >-
        {% if states.binary_sensor.hallway_door.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.hallway_door.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}

- platform: template
  sensors:
    hallway_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.hallway_temperature.attributes.battery_level }}"
      icon_template: >-
        {% if states.sensor.hallway_temperature.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.sensor.hallway_temperature.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}

- platform: template
  sensors:
    hallway_door:
      friendly_name: Hallway Door
      value_template: >- # Prepare for lock
        {% if is_state('binary_sensor.hallway_door', 'off') %}
          Closed
        {% elif is_state('binary_sensor.hallway_door', 'on') %}
          Open
        {% endif %}
      icon_template: >- # icon_template not working with entity_picture_template
        {% if is_state('binary_sensor.hallway_door', 'off') %}
          mdi:door-closed
        {% elif is_state('binary_sensor.hallway_door', 'on') %}
          mdi:door-open
        {% endif %}
