- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - pressure
    - humidity

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: load_1m
  - type: load_5m
  - type: load_15m
  - type: memory_free
  - type: memory_use
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: ipv4_address
    arg: eth0
  - type: last_boot

- platform: waze_travel_time
  origin: device_tracker.jerjako_mi9
  destination: zone.home
  region: EU
  name: Travel time to home

# Sensor for monitoring the bridge state
- platform: mqtt
  name: Zigbee2mqtt Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
# Sensor for Showing the Zigbee2mqtt Version
- platform: mqtt
  name: Zigbee2mqtt Version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.version }}"
  icon: mdi:zigbee
# Sensor for Showing the Coordinator Version
- platform: mqtt
  name: Coordinator Version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.coordinator }}"
  icon: mdi:chip
