- platform: template
  sensors:
    kitchen_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.kitchen_temperature.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    fridge_thermometer_battery:
      friendly_name: Fridge Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.fridge_temperature.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    freezer_thermometer_battery:
      friendly_name: Freezer Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.freezer_temperature.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    kitchen_door_1_battery:
      friendly_name: Door 1
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.kitchen_door_1.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    kitchen_door_2_battery:
      friendly_name: Door 2
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.kitchen_door_2.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    kitchen_water_leak_battery:
      friendly_name: Water leak
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.kitchen_water_leak.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    kitchen_door:
      friendly_name: Kitchen Door
      value_template: >-
        {% if is_state('binary_sensor.kitchen_door_1', 'off') and is_state('binary_sensor.kitchen_door_2', 'off') %}
          Closed
        {% elif is_state('binary_sensor.kitchen_door_2', 'on') %}
          Open
        {% elif is_state('binary_sensor.kitchen_door_1', 'on') %}
          Half open
        {% endif %}
      entity_picture_template: >- # icon_template not working with entity_picture_template
        {% if is_state('binary_sensor.kitchen_door_1', 'off') and is_state('binary_sensor.kitchen_door_2', 'off') %}
          /local/window_closed.png
        {% elif is_state('binary_sensor.kitchen_door_2', 'on') %}
          /local/window_open.png
        {% elif is_state('binary_sensor.kitchen_door_1', 'on') %}
          /local/window_half_open.png
        {% endif %}
