- platform: template
  sensors:
    landing_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.landing_temperature.attributes.battery_level }}"
      icon_template: >-
        {% if states.sensor.landing_temperature.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.sensor.landing_temperature.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}

- platform: template
  sensors:
    landing_window:
      friendly_name: Landing Window
      value_template: >-
        {% if is_state('binary_sensor.landing_window_1', 'off') and is_state('binary_sensor.landing_window_2', 'off') %}
          Closed
        {% elif is_state('binary_sensor.landing_window_2', 'on') %}
          Open
        {% elif is_state('binary_sensor.landing_window_1', 'on') %}
          Half open
        {% endif %}
      entity_picture_template: >- # icon_template not working with entity_picture_template
        {% if is_state('binary_sensor.landing_window_1', 'off') and is_state('binary_sensor.landing_window_2', 'off') %}
          /local/window_closed.png
        {% elif is_state('binary_sensor.landing_window_2', 'on') %}
          /local/window_open.png
        {% elif is_state('binary_sensor.landing_window_1', 'on') %}
          /local/window_half_open.png
        {% endif %}

- platform: template
  sensors:
    landing_window_1_battery:
      friendly_name: Window 1
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.landing_window_1.attributes.battery_level }}"
      icon_template: >-
        {% if states.binary_sensor.landing_window_1.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.landing_window_1.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}

- platform: template
  sensors:
    landing_window_2_battery:
      friendly_name: Window 2
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.landing_window_2.attributes.battery_level }}"
      icon_template: >-
        {% if states.binary_sensor.landing_window_2.attributes.battery_level <= 10 %}
          mdi:battery-10
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 20 %}
          mdi:battery-20
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 30 %}
          mdi:battery-30
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 40 %}
          mdi:battery-40
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 50 %}
          mdi:battery-50
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 60 %}
          mdi:battery-60
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 70 %}
          mdi:battery-70
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 80 %}
          mdi:battery-80
        {% elif states.binary_sensor.landing_window_2.attributes.battery_level <= 90 %}
          mdi:battery-90
        {% else %}
          mdi:battery
        {% endif %}
