- platform: template
  sensors:
    loft_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.loft_temperature.attributes.battery_level }}"
      device_class: battery
