- platform: template
  sensors:
    loft_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.loft_temperature.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    loft_window_battery:
      friendly_name: Window
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.loft_window.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    loft_window:
      friendly_name: Loft Window
      value_template: >- # Prepare for lock
        {% if is_state('binary_sensor.loft_window', 'off') %}
          Closed
        {% elif is_state('binary_sensor.loft_window', 'on') %}
          Open
        {% endif %}
      icon_template: >- # icon_template not working with entity_picture_template
        {% if is_state('binary_sensor.loft_window', 'off') %}
          /local/window_closed.png
        {% elif is_state('binary_sensor.loft_window', 'on') %}
          /local/window_open.png
        {% endif %}
