- platform: template
  sensors:
    wc_motion_sensor_battery:
      friendly_name: Motion sensor
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.wc_motion_sensor.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    wc_thermometer_battery:
      friendly_name: Thermometer
      unit_of_measurement: "%"
      value_template: "{{ states.sensor.wc_temperature.attributes.battery_level }}"
      device_class: battery

- platform: template
  sensors:
    wc_water_leak_battery:
      friendly_name: Water leak
      unit_of_measurement: "%"
      value_template: "{{ states.binary_sensor.wc_water_leak.attributes.battery_level }}"
      device_class: battery
